name: Continuous Integration and Deployment (CI/CD)

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '5.0.x'   # set this to the dot net version to use
  AZURE_WEBAPP_NAME: eepocapi   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  AZURE_RESOURCE_GROUP_NAME: 'ExtraaEdge-Dev-Free-RG'   #set this to the name of the azure resource group

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@master

      # Setup .NET Core SDK
      - name: Setup .NET Core 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish "./Sample-CI-CD.csproj" -c Release -o website 
          
      # Upload a Build Artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: website
          path: ./website/**
          if-no-files-found: error

     
    
  